"""Add annual dividend per share to jq_statements (total-return / dividend yield)

Adds:
  - jq_statements.dividend_per_share_annual  (Numeric(18,4), nullable)

Sourced from the on-plan /fins/summary statements payload (field DivAnn /
ResultDividendPerShareAnnual); the dedicated /fins/dividend endpoint is premium-only.
Used by the value-tilt probe to correct adj_close's dividend omission (value names
are high-yield → their total return was understated).

Hand-written (not autogenerated) to avoid pulling in unrelated schema drift from the
partitioned ohlcv_1d_yXXXX tables (see CLAUDE.md § DB Schema Changes).

Revision ID: a1c4e7f93b2d
Revises: d7e2c9a4f1b8
Create Date: 2026-05-28
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1c4e7f93b2d'
down_revision: Union[str, Sequence[str], None] = 'd7e2c9a4f1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("jq_statements",
                  sa.Column("dividend_per_share_annual", sa.Numeric(18, 4), nullable=True))


def downgrade() -> None:
    op.drop_column("jq_statements", "dividend_per_share_annual")
