"""J-Quants data tables (parallel jq_-prefixed source)

Creates the J-Quants collector's tables: jq_listed, jq_daily_quotes,
jq_statements, jq_topix, jq_trading_calendar, jq_fetch_cursor. These coexist with
the existing yfinance-fed stocks/ohlcv_1d schema and do not touch it.

Hand-written (not autogenerated) to avoid pulling in unrelated schema drift from
the partitioned ohlcv_1d_yXXXX tables (see CLAUDE.md § DB Schema Changes).

Revision ID: c3f1a8b6d2e9
Revises: f4b1d8c3a907
Create Date: 2026-05-24
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c3f1a8b6d2e9'
down_revision: Union[str, Sequence[str], None] = 'f4b1d8c3a907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PRICE = sa.Numeric(14, 4)
_YEN = sa.Numeric(22, 2)


def upgrade() -> None:
    op.create_table(
        "jq_listed",
        sa.Column("code", sa.String(10), primary_key=True),
        sa.Column("date", sa.Date()),
        sa.Column("company_name", sa.String(500)),
        sa.Column("company_name_en", sa.String(500)),
        sa.Column("sector17_code", sa.String(10)),
        sa.Column("sector17_name", sa.String(200)),
        sa.Column("sector33_code", sa.String(10)),
        sa.Column("sector33_name", sa.String(200)),
        sa.Column("scale_category", sa.String(100)),
        sa.Column("market_code", sa.String(10)),
        sa.Column("market_code_name", sa.String(100)),
        sa.Column("updated_at", sa.DateTime(timezone=True)),
    )

    op.create_table(
        "jq_daily_quotes",
        sa.Column("code", sa.String(10), primary_key=True),
        sa.Column("date", sa.Date(), primary_key=True),
        sa.Column("open", _PRICE),
        sa.Column("high", _PRICE),
        sa.Column("low", _PRICE),
        sa.Column("close", _PRICE),
        sa.Column("volume", sa.BigInteger()),
        sa.Column("turnover_value", _YEN),
        sa.Column("adjustment_factor", sa.Numeric(18, 8)),
        sa.Column("adj_open", _PRICE),
        sa.Column("adj_high", _PRICE),
        sa.Column("adj_low", _PRICE),
        sa.Column("adj_close", _PRICE),
        sa.Column("adj_volume", sa.BigInteger()),
    )

    op.create_table(
        "jq_statements",
        sa.Column("disclosure_number", sa.String(20), primary_key=True),
        sa.Column("local_code", sa.String(10), nullable=False),
        sa.Column("disclosed_date", sa.Date(), nullable=False),
        sa.Column("disclosed_time", sa.Time()),
        sa.Column("announcement_date", sa.Date(), nullable=False),
        sa.Column("type_of_document", sa.String(100)),
        sa.Column("type_of_current_period", sa.String(10)),
        sa.Column("current_period_start_date", sa.Date()),
        sa.Column("current_period_end_date", sa.Date()),
        sa.Column("current_fiscal_year_start_date", sa.Date()),
        sa.Column("current_fiscal_year_end_date", sa.Date()),
        sa.Column("net_sales", _YEN),
        sa.Column("operating_profit", _YEN),
        sa.Column("ordinary_profit", _YEN),
        sa.Column("profit", _YEN),
        sa.Column("earnings_per_share", sa.Numeric(18, 4)),
        sa.Column("forecast_operating_profit", _YEN),
        sa.Column("forecast_ordinary_profit", _YEN),
        sa.Column("forecast_profit", _YEN),
        sa.Column("forecast_earnings_per_share", sa.Numeric(18, 4)),
        sa.Column("total_assets", _YEN),
        sa.Column("equity", _YEN),
        sa.Column("equity_to_asset_ratio", sa.Numeric(10, 6)),
        sa.Column("book_value_per_share", sa.Numeric(18, 4)),
        sa.Column("shares_outstanding_fy", sa.BigInteger()),
        sa.Column("treasury_shares_fy", sa.BigInteger()),
        sa.Column("average_shares", sa.Numeric(20, 2)),
        sa.Column("retrieved_at", sa.DateTime(timezone=True)),
    )
    op.create_index("ix_jq_statements_code_disc", "jq_statements",
                    ["local_code", "disclosed_date"])
    op.create_index("ix_jq_statements_period", "jq_statements",
                    ["local_code", "type_of_current_period", "current_period_end_date"])

    op.create_table(
        "jq_topix",
        sa.Column("date", sa.Date(), primary_key=True),
        sa.Column("open", _PRICE),
        sa.Column("high", _PRICE),
        sa.Column("low", _PRICE),
        sa.Column("close", _PRICE),
    )

    op.create_table(
        "jq_trading_calendar",
        sa.Column("date", sa.Date(), primary_key=True),
        sa.Column("holiday_division", sa.String(2)),
    )

    op.create_table(
        "jq_fetch_cursor",
        sa.Column("endpoint", sa.String(40), primary_key=True),
        sa.Column("last_date", sa.Date()),
        sa.Column("last_pagination_key", sa.String(500)),
        sa.Column("updated_at", sa.DateTime(timezone=True)),
    )


def downgrade() -> None:
    op.drop_table("jq_fetch_cursor")
    op.drop_table("jq_trading_calendar")
    op.drop_table("jq_topix")
    op.drop_index("ix_jq_statements_period", table_name="jq_statements")
    op.drop_index("ix_jq_statements_code_disc", table_name="jq_statements")
    op.drop_table("jq_statements")
    op.drop_table("jq_daily_quotes")
    op.drop_table("jq_listed")
