"""sign_feature_runs + sign_feature_records

Persist the per-fire enrichment table produced by src/analysis/sign_features.py
(indicator distances, correlations, co-fire / N225 directional counts, forward
outcomes, plus full per-sign score maps as JSONB). Previously these lived only
in an ephemeral /tmp pickle; sign scores themselves are already durable in
sign_benchmark_events.

Hand-written (not autogenerated) to avoid picking up partitioned-OHLCV drift.

Revision ID: d3f9a1c7e2b8
Revises: c2e8f4a9d1b6
Create Date: 2026-05-20
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'd3f9a1c7e2b8'
down_revision: Union[str, Sequence[str], None] = 'c2e8f4a9d1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'sign_feature_runs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('label', sa.String(length=64), nullable=False),
        sa.Column('fwd_h', sa.Integer(), nullable=False),
        sa.Column('valid_bars', sa.Integer(), nullable=False),
        sa.Column('corr_window', sa.Integer(), nullable=False),
        sa.Column('n_records', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'sign_feature_records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('run_id', sa.Integer(), nullable=False),
        sa.Column('stock_code', sa.String(length=30), nullable=False),
        sa.Column('fired_on', sa.Date(), nullable=False),
        sa.Column('fy', sa.String(length=8), nullable=False),
        sa.Column('sign_type', sa.String(length=32), nullable=False),
        sa.Column('sign_score', sa.Float(), nullable=True),
        sa.Column('sma_dist', sa.Float(), nullable=True),
        sa.Column('kumo_dist', sa.Float(), nullable=True),
        sa.Column('chiko_dist', sa.Float(), nullable=True),
        sa.Column('tenkan_dist', sa.Float(), nullable=True),
        sa.Column('zz_momentum', sa.Float(), nullable=True),
        sa.Column('corr_n225', sa.Float(), nullable=True),
        sa.Column('corr_gspc', sa.Float(), nullable=True),
        sa.Column('corr_hsi', sa.Float(), nullable=True),
        sa.Column('valid_n', sa.Integer(), nullable=True),
        sa.Column('bullish_valid_n', sa.Integer(), nullable=True),
        sa.Column('bearish_valid_n', sa.Integer(), nullable=True),
        sa.Column('n225_bullish_n', sa.Integer(), nullable=True),
        sa.Column('n225_bearish_n', sa.Integer(), nullable=True),
        sa.Column('out_direction', sa.Integer(), nullable=True),
        sa.Column('out_bars', sa.Integer(), nullable=True),
        sa.Column('out_magnitude', sa.Float(), nullable=True),
        sa.Column('fwd_ret_h', sa.Float(), nullable=True),
        sa.Column('cofire_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('n225_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['sign_feature_runs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_sfr_run', 'sign_feature_records', ['run_id'])
    op.create_index('ix_sfr_stock', 'sign_feature_records', ['run_id', 'stock_code'])
    op.create_index('ix_sfr_sign', 'sign_feature_records', ['run_id', 'sign_type'])
    op.create_index('ix_sfr_fy', 'sign_feature_records', ['run_id', 'fy'])


def downgrade() -> None:
    op.drop_index('ix_sfr_fy', table_name='sign_feature_records')
    op.drop_index('ix_sfr_sign', table_name='sign_feature_records')
    op.drop_index('ix_sfr_stock', table_name='sign_feature_records')
    op.drop_index('ix_sfr_run', table_name='sign_feature_records')
    op.drop_table('sign_feature_records')
    op.drop_table('sign_feature_runs')
