"""Order/Entry/Cancel position workflow + account budget

Adds the pre-fill "ordered" state to positions and a per-account trading budget for
lot-aware sizing:
  - accounts.budget        (Numeric(14,2), nullable)
  - positions.order_date   (Date, nullable)
  - positions.order_price  (Numeric(12,2), nullable)
  - positions.entry_date / positions.entry_price -> NULLABLE (an ordered-but-unfilled
    row has no real entry yet). status now takes ordered|open|closed|cancelled (the
    String(10) column already fits these — no type change).

Hand-written (not autogenerated) to avoid pulling in unrelated schema drift from the
partitioned ohlcv_1d_yXXXX tables (see CLAUDE.md § DB Schema Changes).

Revision ID: d7e2c9a4f1b8
Revises: c3f1a8b6d2e9
Create Date: 2026-05-24
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7e2c9a4f1b8'
down_revision: Union[str, Sequence[str], None] = 'c3f1a8b6d2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("accounts", sa.Column("budget", sa.Numeric(14, 2), nullable=True))
    op.add_column("positions", sa.Column("order_date", sa.Date(), nullable=True))
    op.add_column("positions", sa.Column("order_price", sa.Numeric(12, 2), nullable=True))
    op.alter_column("positions", "entry_date", existing_type=sa.Date(), nullable=True)
    op.alter_column("positions", "entry_price",
                    existing_type=sa.Numeric(12, 2), nullable=True)


def downgrade() -> None:
    # Re-imposing NOT NULL requires no ordered/cancelled rows to exist; back-fill or
    # drop them before downgrading.
    op.alter_column("positions", "entry_price",
                    existing_type=sa.Numeric(12, 2), nullable=False)
    op.alter_column("positions", "entry_date", existing_type=sa.Date(), nullable=False)
    op.drop_column("positions", "order_price")
    op.drop_column("positions", "order_date")
    op.drop_column("accounts", "budget")
