"""accounts table + account_id on positions / reviewed_candidates

Adds the `accounts` table and a nullable `account_id` FK on both
`positions` and `reviewed_candidates`.  Creates a "default" account
and backfills all existing rows to it so historical data stays
addressable.

Manual migration (not autogenerated) to avoid OHLCV partition drift
per CLAUDE.md.

Revision ID: e6a3b8d2c1f4
Revises: d2e5b7c9a0f3
Create Date: 2026-05-16
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e6a3b8d2c1f4'
down_revision: Union[str, Sequence[str], None] = 'd2e5b7c9a0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'accounts',
        sa.Column('id',           sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column('name',         sa.String(60),   nullable=False, unique=True),
        sa.Column('description',  sa.Text(),       nullable=True),
        sa.Column('initial_cash', sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column('archived',     sa.Boolean(),    nullable=False, server_default=sa.false()),
        sa.Column('created_at',   sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
    )

    op.add_column(
        'positions',
        sa.Column('account_id', sa.BigInteger(),
                  sa.ForeignKey('accounts.id', ondelete='SET NULL'),
                  nullable=True),
    )
    op.create_index('ix_positions_account_id', 'positions', ['account_id'])

    op.add_column(
        'reviewed_candidates',
        sa.Column('account_id', sa.BigInteger(),
                  sa.ForeignKey('accounts.id', ondelete='SET NULL'),
                  nullable=True),
    )
    op.create_index('ix_reviewed_candidates_account_id',
                    'reviewed_candidates', ['account_id'])

    # ── Backfill: create default account + assign existing rows ─────────────
    conn = op.get_bind()
    default_id = conn.execute(sa.text(
        "INSERT INTO accounts (name, description) "
        "VALUES ('default', 'Auto-created during migration; "
        "holds positions and reviews from before multi-account support.') "
        "RETURNING id"
    )).scalar()
    conn.execute(sa.text(
        "UPDATE positions SET account_id = :aid WHERE account_id IS NULL"
    ), {"aid": default_id})
    conn.execute(sa.text(
        "UPDATE reviewed_candidates SET account_id = :aid WHERE account_id IS NULL"
    ), {"aid": default_id})


def downgrade() -> None:
    op.drop_index('ix_reviewed_candidates_account_id', table_name='reviewed_candidates')
    op.drop_column('reviewed_candidates', 'account_id')
    op.drop_index('ix_positions_account_id', table_name='positions')
    op.drop_column('positions', 'account_id')
    op.drop_table('accounts')
