"""widen sign_type to 255 on positions + reviewed_candidates

ConfluenceSignStrategy stores its full "conf{N}:{constituents}" label in
sign_type (e.g. conf6:brk_kumo_hi,brk_tenkan_hi,chiko_hi,rev_lo,str_hold,
str_lag), which can reach ~100 chars. The columns were varchar(30) — sized for
single-sign regime labels — so registering or skipping a confluence proposal
raised StringDataRightTruncation. Widen both to varchar(255).

Hand-written (not autogenerated) to avoid pulling in unrelated schema drift from
the partitioned ohlcv_1d_yXXXX tables.

Revision ID: f4b1d8c3a907
Revises: e5a2c9b14f37
Create Date: 2026-05-22
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4b1d8c3a907'
down_revision: Union[str, Sequence[str], None] = 'e5a2c9b14f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('positions', 'sign_type',
                    existing_type=sa.String(length=30),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('reviewed_candidates', 'sign_type',
                    existing_type=sa.String(length=30),
                    type_=sa.String(length=255),
                    existing_nullable=False)


def downgrade() -> None:
    # NOTE: down-migrating after a confluence label was stored would truncate it.
    op.alter_column('reviewed_candidates', 'sign_type',
                    existing_type=sa.String(length=255),
                    type_=sa.String(length=30),
                    existing_nullable=False)
    op.alter_column('positions', 'sign_type',
                    existing_type=sa.String(length=255),
                    type_=sa.String(length=30),
                    existing_nullable=False)
